package com.kma.musicplayer.model

import com.kma.musicplayer.R

enum class Theme(
    val primaryColorRes: Int,
    val backgroundColorRes: Int,
    val titleTextColorRes: Int,
    val activeTabTextColorRes: Int,
    val inactiveTabTextColorRes: Int,
    val adapterTitleTextColorRes: Int,
    val imageCheckBoxRes: Int,
    val imageSortRes: Int,
    val cardBackgroundColorRes: Int,
    val imageMenuRes: Int,
    val adapterSubTitleTextColorRes: Int,
    val imagePlusCircle: Int,
    val imageBackButtonRes: Int,
    val descriptionTextColorRes: Int,
    val backgroundPlayButtonRes: Int,
    val editTextBackgroundColorRes: Int,
    val imageSearchRes: Int,
    val imageCheckBoxSelectedRes: Int,
    val imageCheckBoxUnSelectedRes: Int,
    val imageShareRes: Int,
    val imageNoFavoriteRes: Int,
    val unPlayedTimerBarColor: Int,
    val settingIconColorRes: Int,
    val backgroundSettingTabRes: Int,
    val imageLanguageItemBackgroundRes: Int,
    val languageItemTextColorRes: Int,
    val dividerColorRes: Int,
    val bottomMiniPlayerBackgroundRes: Int,
    val songQueueIconColorRes: Int,
) {
    LIGHT(
        primaryColorRes = R.color.color_1E232E,
        backgroundColorRes = R.color.white,
        titleTextColorRes = R.color.color_1E232E,
        activeTabTextColorRes = R.color.color_1E232E,
        inactiveTabTextColorRes = R.color.color_787B82,
        adapterTitleTextColorRes = R.color.color_4B4F58,
        imageCheckBoxRes = R.drawable.ic_checkbox_light_theme,
        imageSortRes = R.drawable.ic_sort_light_theme,
        cardBackgroundColorRes = R.color.color_D2D3D5,
        imageMenuRes = R.drawable.ic_menu_light_theme,
        adapterSubTitleTextColorRes = R.color.color_7150D0,
        imagePlusCircle = R.drawable.ic_plus_circle_light_theme,
        imageBackButtonRes = R.drawable.ic_arrow_back_light_theme,
        descriptionTextColorRes = R.color.color_4B4F58,
        backgroundPlayButtonRes = R.drawable.bg_favourite_play_button_light_theme,
        editTextBackgroundColorRes = R.color.color_F3F4F6,
        imageSearchRes = R.drawable.ic_search_light_theme,
        imageCheckBoxSelectedRes = R.drawable.ic_check_box_selected_light_theme,
        imageCheckBoxUnSelectedRes = R.drawable.ic_check_box_unselected_light_theme,
        imageShareRes = R.drawable.ic_share_light_theme,
        imageNoFavoriteRes = R.drawable.ic_black_heart,
        unPlayedTimerBarColor = R.color.black_20,
        settingIconColorRes = R.color.color_7150D0,
        backgroundSettingTabRes = R.drawable.bg_setting_tab_light_theme,
        imageLanguageItemBackgroundRes = R.drawable.border_item_language_light_theme,
        languageItemTextColorRes = R.color.color_0F0817,
        dividerColorRes = R.color.color_F1F1F1,
        bottomMiniPlayerBackgroundRes = R.drawable.bg_bottom_mini_player_light_theme,
        songQueueIconColorRes = R.color.color_4B4F58
    ),
    DARK(
        primaryColorRes = R.color.white,
        backgroundColorRes = R.color.color_0F0817,
        titleTextColorRes = R.color.white,
        activeTabTextColorRes = R.color.white,
        inactiveTabTextColorRes = R.color.color_787B82,
        adapterTitleTextColorRes = R.color.color_D2D3D5,
        imageCheckBoxRes = R.drawable.ic_checkbox,
        imageSortRes = R.drawable.ic_sort,
        cardBackgroundColorRes = R.color.color_40434A,
        imageMenuRes = R.drawable.ic_menu,
        adapterSubTitleTextColorRes = R.color.white,
        imagePlusCircle = R.drawable.ic_plus_circle,
        imageBackButtonRes = R.drawable.ic_arrow_back,
        descriptionTextColorRes = R.color.color_D2D3D5,
        backgroundPlayButtonRes = R.drawable.bg_favourite_play_button,
        editTextBackgroundColorRes = R.color.color_242635,
        imageSearchRes = R.drawable.ic_search,
        imageCheckBoxSelectedRes = R.drawable.ic_select_all_enable,
        imageCheckBoxUnSelectedRes = R.drawable.ic_checkbox_unselected,
        imageShareRes = R.drawable.ic_share,
        imageNoFavoriteRes = R.drawable.ic_white_heart,
        unPlayedTimerBarColor = R.color.white_20,
        settingIconColorRes = R.color.color_787B82,
        backgroundSettingTabRes = R.drawable.bg_setting_tab,
        imageLanguageItemBackgroundRes = R.drawable.border_item_language,
        languageItemTextColorRes = R.color.white,
        dividerColorRes = R.color.color_1E232E,
        bottomMiniPlayerBackgroundRes = R.drawable.bg_bottom_mini_player,
        songQueueIconColorRes = R.color.color_A5A7AB
    ),
}