package com.kma.musicplayer.utils

object Constant {
    const val BUNDLE_SONGS = "BUNDLE_SONGS"
    const val BUNDLE_SONG_STATUS = "BUNDLE_SONG_STATUS"
    const val BUNDLE_START_FROM_INDEX = "BUNDLE_START_FROM_INDEX"
    const val BUNDLE_IS_FROM_BOTTOM_MINI_PLAYER = "BUNDLE_IS_FROM_BOTTOM_MINI_PLAYER"
    const val BUNDLE_ARTIST = "BUNDLE_ARTIST"

    const val REQUEST_CODE_DATA_CHANGED = 100
}